apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: url-service-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10