apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: url-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: url-service
    template:
      metadata:
        labels:
          app: url-service
      spec:
        containers:
        - name: url-service
          image: l8518/wsacs-url-shortener:latest
          ports: 
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
            requests:
              memory: "250Mi"
              cpu: "100m"
- apiVersion: v1
  kind: Service
  metadata:
    name: url-service-service
  spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
    selector:
      app: url-service

