version: '2.2'
services:
  loadbalancer:
    image: l8518/wsacs-reverseproxy:latest
    volumes:
      - ./reverseproxy/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - services
    depends_on:
      - default.url-shortener
      - default.user-service
  default.user-service:
    image: l8518/wsacs-userservice:latest
    networks:
      - services
  default.url-shortener:
    image: l8518/wsacs-url-shortener:latest
    networks:
      - services
  01.url-shortener:
    image: l8518/wsacs-url-shortener:latest
    networks:
      - services
networks:
  services:
    driver: bridge
