version: '2.2'
services:
  registry:
    build:
      context: server/registry/ 
    image: l8518/wsacs-registry:${TAG-latest}
  userservice:
    build:
      context: server/user-service/
    image: l8518/wsacs-userservice:${TAG-latest}
  url-shortener:
    build:
      context: server/url-shorten-service/
    image: l8518/wsacs-url-shortener:${TAG-latest}
