apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: url-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: url-service
    template:
      metadata:
        labels:
          app: url-service
      spec:
        containers:
        - name: url-service
          image: l8518/wsacs-url-shortener:latest
          ports:
          - containerPort: 8083
- apiVersion: v1
  kind: Service
  metadata:
    name: url-service
  spec:
    selector:
      app: url-service
    ports:
      - protocol: TCP
        port: 8083
        targetPort: 8083
    type: NodePort