apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: userservice
        image: l8518/wsacs-userservice:${TAG-latest}
        ports:
        - containerPort: 8083                                                                                                                                  20,0-1        All
