apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: user-service
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: user-service
    template:
      metadata:
        labels:
          app: user-service
      spec:
        containers:
        - name: user-service
          image: l8518/wsacs-userservice:latest
          ports:
          - containerPort: 8083
- apiVersion: v1
  kind: Service
  metadata:
    name: user-service
  spec:
    ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
    selector:
      app: user-service
    type: NodePort
