name: Docker Image CI

on:
  push:
    branches: 
      - master
      - feature/k8s
      - feature/k8s-improvements

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Container
        run: |
          docker-compose -f docker-compose.build.yml build
          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker-compose -f docker-compose.build.yml build
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Container
        run: |
          docker-compose -f docker-compose.build.yml push
          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker-compose -f docker-compose.build.yml push
      - name: Log out
        run: |
          docker logout