name: Docker Image CI

on:
  push:
    branches: [ feature/container ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Container
        run: |
          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          echo $TAG
          docker-compose build
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Container
        run: |
          docker-compose push
      - name: Log out
        run: |
          docker logout